<!-- 
/*!
* Gidola Zend Framework 1.x Grid
* Copyright(c) 2011 Tom Shaw <tom@tomshaw.info>
* MIT Licensed
*/
-->
<?php $colspan = count($this->datagrid); ?>
<?php if(sizeof($this->massactions)): $colspan++; endif; ?>
<?php if(sizeof($this->actions)): $colspan++; endif; ?>
<form method="post" id="<?php echo $this->formid ?>" action="<?php echo $this->url ?>">
<?php if(sizeof($this->massactions) && sizeof($this->actions)): ?>
<fieldset style="float:right;margin-top:10px;margin-right:5px;">Actions <select id="massaction">
  <option value="-1"></option>
  <?php foreach($this->massactions as $_index => $value): ?>
  <option value="<?php echo $_index ?>"><?php echo $value['label'] ?></option>
  <?php endforeach; ?>
</select> <input class="button2" type="submit" value="Go"> <input type="submit" name="submit" value="Filter Results"></fieldset>
<?php else: ?>
<div style="float:right;margin-top:10px;margin-right:5px;"><input type="submit" name="submit" value="Filter Results"></div>
<?php endif;?>
<?php if(sizeof($this->rows)): ?>
<?php echo $this->paginationControl($this->rows, $this->scrolltype, $this->paginatorpartial); ?>
<?php endif; ?>
<table <?php if($this->tableclass): ?>class="<?php echo $this->tableclass ?>"<?php endif; ?>>
  <thead>
    <tr>
      <?php if(sizeof($this->massactions)): ?><th style="width:50px;text-align:center;">Check</th><?php endif; ?>
      <?php foreach($this->datagrid as $element): ?>
      <th <?php echo $element['style'] ?>><a href="<?php echo $this->url; ?>order/<?php echo $element['index']; ?>/page/<?php echo $this->page; ?>/sort/<?php echo $this->sort; ?>"><?php echo $element['header']; ?></a></th>
      <?php endforeach; ?>
      <?php if(sizeof($this->actions)): ?><th style="width:10%;text-align:center;">Actions</th><?php endif; ?>
    </tr>
  </thead>
  <tbody>
    <?php if($this->showfilter): ?>
    <tr>
      <?php if(sizeof($this->massactions)): ?><td style="text-align:center;"><input type="checkbox" id="checkall" value=""></td><?php endif; ?>
      <?php foreach($this->datagrid as $element): ?>
      <td <?php echo $element['style'] ?>><?php echo $element['element']; ?></td>
      <?php endforeach; ?>
      <?php if(sizeof($this->actions)): ?><td>&nbsp;</td><?php endif; ?>
    </tr>
    <?php endif; ?>
    <?php if(sizeof($this->rows)): ?>
    <?php foreach($this->rows as $_index => $value): ?>
    <?php $data = $value->toArray(); ?>
    <?php $colour = $this->cycle(sizeof($this->cyclecolors) ? $this->cyclecolors : array())->next(); ?>
    <tr <?php if(sizeof($this->rowclickurl)): ?>data-href="<?php echo $this->rowclickurl['url'] ?><?php if(isset($data[$this->rowclickurl['field']])): echo urlencode($this->escape($data[$this->rowclickurl['field']])) ?><?php endif; ?>"<?php endif; ?> style="background-color:<?= $colour ?>" <?php if($this->onmouseovercolor): ?>onmouseover="this.style.background='<?php echo $this->onmouseovercolor ?>';"<?php endif; ?> <?php if($this->onmouseovercolor): ?>onmouseout="this.style.background='<?= $colour ?>';"<?php endif; ?>>
      <?php $hasMassActionCheckBox = false; ?>
      <?php if(sizeof($this->massactions) && $hasMassActionCheckBox === false): ?>
      <td style="text-align:center;">
        <?php if(isset($data[$this->massactionfield])): ?>
        <input type="checkbox" name="selected[]" value="<?php echo urlencode($this->escape($data[$this->massactionfield])); ?>">
        <?php $hasMassActionCheckBox = true; ?>
        <?php endif; ?>  
      </td>
      <?php endif; ?>
      <?php foreach($this->datagrid as $column): ?>
      <?php if(array_key_exists($column['index'], $data)): ?>
      <td <?php echo $column['style'] ?>><?php echo $this->escape($data[$column['index']]); ?></td>
      <?php continue; ?>
      <?php endif; ?>
      <?php endforeach; ?>
      <?php if(sizeof($this->actions)): ?>
      <td style="text-align:center;">
      <?php $i = 1; foreach($this->actions as $action): ?>
      	<a href="<?php echo $action['url']; ?>/<?php echo $action['field']; ?>/<?php echo urlencode($this->escape($data[$action['field']])); ?>" <?php if(isset($action['title'])): ?>title="<?php echo $action['title']; ?>"<?php endif; ?>><?php echo $action['label']; ?></a><?php if($i<count($this->actions)): ?> | <?php endif; ?>
      <?php $i++; endforeach; ?>
      </td>
      <?php endif; ?>
    </tr>
    <?php endforeach; ?>
    <?php else: ?>
    <tr>
      <td colspan="<?php echo $colspan ?>">There were no results returned.</td>
    </tr>
    <?php endif; ?>
  </tbody>
</table>
</form>