<?php if ($this->pageCount): ?>
<div class="dataTables_paginate paging_bootstrap pagination">
  <ul>
    <li class="prev"><a href="#">Results: <?= $this->firstItemNumber; ?>/<?= $this->lastItemNumber; ?></a></li>
    <li class="prev"><a href="#">Total: <?= $this->totalItemCount; ?></a></li>
  </ul>
  <ul>
    <?php if (isset($this->previous)): ?>
    <li class="prev"><a href="<?= $this->url(array('page' => $this->first)); ?>">First</a></li>
    <?php else: ?>
    <li class="prev disabled"><a href="#">First</a></li>
    <?php endif; ?>
    <?php if (isset($this->previous)): ?>
    <li><a href="<?= $this->url(array('page' => $this->previous)); ?>">&larr; Previous</a></li>
    <?php else: ?>
    <li class="prev disabled"><a href="#">Previous</a></li>
    <?php endif; ?>
    <?php foreach ($this->pagesInRange as $page): ?>
    <li <?php if ($page == $this->current): ?>class="active"<?php endif; ?>><a href="<?= $this->url(array('page' => $page)); ?>"><?= $page; ?></a></li> 
    <?php endforeach; ?>
    <?php if (isset($this->next)): ?>
    <li class="next"><a href="<?= $this->url(array('page' => $this->next)); ?>">Next &rarr;</a></li>
    <?php else: ?>
    <li class="next disabled"><a href="#">Next</a></li>
    <?php endif; ?>
    <?php if (isset($this->next)): ?>
    <li class="next"><a href="<?= $this->url(array('page' => $this->last)); ?>">Last</a></li>
    <?php else: ?>
    <li class="next disabled"><a href="#">Last</a></li>
    <?php endif; ?>
  </ul>
</div>
<?php endif; ?>