<div style="width:95%;margin:0 auto;">
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th style="text-align: center; width:5%;">Count</th>
      <th style="text-align: left; width:80%;">&nbsp;SQL Statement</th>
      <th style="text-align: left; width:15%;">Time</th>
    </tr>
  </thead>
  <tbody>
  	<?php foreach($this->queries as $out): ?>
    <tr>
      <td style="text-align: center;"><?= $out['count'] ?>.</td>
      <td><?= $out['query'] ?></td>
      <td><i><?= $out['seconds'] ?></i></td>
    </tr>
    <?php endforeach; ?>
  </tbody>
</table>
</div>
<div style="width:95%;margin:0 auto;">
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th style="text-align:left; width: 85%">&nbsp;Statistic</th>
      <th style="text-align:left; width: 15%">Value</th>
    </tr>
  </thead>	
  <tbody>
    <tr>
      <td>Total milliseconds:</td>
      <td style="text-align:left;"><?= $this->elapsedMilliSeconds ?></td>
    </tr>
    <tr>
      <td>Average query time:</td>
      <td style="text-align:left;"><?= $this->averageQueryTime ?></td>
    </tr>
    <tr>
      <td>Queries per second:</td>
      <td style="text-align:left;"><?= $this->queriesPerSecond ?></td>
    </tr>
    <tr>
      <td>Longest query time:</td>
      <td style="text-align:left;"><?= $this->longestQueryTime ?></td>
    </tr>
    <tr>
      <td>Longest query id:</td>
      <td style="text-align:left;">#<?= $this->longestQueryId ?>.</td>
    </tr>
  </tbody>
</table>
</div>