<?php echo $this->docType() ?>
<html lang="en">
<head>
<meta charset="utf-8">
<?php echo $this->headTitle() ?>

<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<?php echo $this->headLink() ?>
<?php echo $this->headStyle() ?>
<?php echo $this->jQuery(); ?>
<?php echo $this->headScript() ?>

<link rel="shortcut icon" href="/images/favicon.ico">
<link rel="apple-touch-icon" href="/images/apple-touch-icon.png">
<link rel="apple-touch-icon" sizes="72x72" href="/images/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="114x114" href="/images/apple-touch-icon-114x114.png">
</head>

<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid"> <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </a> <a class="brand" href="/">Gridola - Zend Framework Grid</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
        <p class="navbar-text pull-right">Logged in as <a href="#">Bruce Lee</a></p>
      </div>
      <!--/.nav-collapse --> 
    </div>
  </div>
</div>
<div class="container">
  <?= $this->inlineScript(); ?>
  <?= $this->layout()->content ?>
  <hr>
  <footer>
    <p>Gridola - Zend Framework Grid &copy; Tom Shaw 2012</p>
  </footer>
</div>

<!-- Le javascript
    ================================================== --> 
<!-- Placed at the end of the document so the pages load faster --> 
<script src="/js/jquery.js"></script> 
<script src="/js/bootstrap-transition.js"></script> 
<script src="/js/bootstrap-alert.js"></script> 
<script src="/js/bootstrap-modal.js"></script> 
<script src="/js/bootstrap-dropdown.js"></script> 
<script src="/js/bootstrap-scrollspy.js"></script> 
<script src="/js/bootstrap-tab.js"></script> 
<script src="/js/bootstrap-tooltip.js"></script> 
<script src="/js/bootstrap-popover.js"></script> 
<script src="/js/bootstrap-button.js"></script> 
<script src="/js/bootstrap-collapse.js"></script> 
<script src="/js/bootstrap-carousel.js"></script> 
<script src="/js/bootstrap-typeahead.js"></script>

<?= $this->placeholder('profiler') ?>
</body>
</html>